### ISSUE TITLE
Casting Via Mobile Hotspot vs WiFi

### ISSUE THREAD

**Issue by blue-pine** [googlecast/CastAndroidTvReceiver#2]
I can cast everything to Google TV cast using wifi , which I can cast  to  Google TV cast using mobile hotspot
, Except screen cast which doesn't work when I cast through any broadband wifi  but works when I cast using mobile hotspot. This issue has not been noticed by Google till now , pls fix it.(I screen cast using Google Home app)

**Comment by jtromo** [comment]
Please report this issue through the issue tracker and provide information about the device you are attempting to screen cast: https://developers.google.com/cast/support#report_issues
