### ISSUE TITLE
Someone Using My WOrkspace to Cast my Screen to their TV

### ISSUE THREAD

**Issue by LarrySOScary** [googlecast/CastAndroidTvReceiver#4]
I need help here, as I don't own an android tablet or TV, but I want to disable ALL google cast functions

**Comment by gomez-andres** [comment]
Hello, this repository's issues are intended for issues detected in the sample code for developers. If you have any Chromecast usage issues please do reach out to the [Chromecast support forums](https://www.googlenestcommunity.com/).
